### ISSUE TITLE
Can you add the AEG AX 9 purifier

### ISSUE THREAD

**Issue by FrankGeraldLieuwen** [tomekkleszcz/homebridge-electrolux-devices#1]
Hi Tom,

A million thanks for the great effort!!
Can you please add the AEG AX9 to the product list?

Cheers

Frank

**Comment by tomekkleszcz** [comment]
Hi @FrankGeraldLieuwen,

Unfortunately, I don't have such device at my home. In order to implement support for AX9, I need to check how the communication between the mobile app and the Electrolux/AEG cloud looks like. Would it be possible for you to change your password to a random one, and send your email and password to me by email: tomekkleszcz[at]icloud.com so I can experiment a little bit and implement the support for it?

Alternatively, if you are not feeling comfortable with sending me the credentials, and you're using iOS you can download the "Proxyman" app from AppStore. If you're using Android just let me know, so I could find another tool to inspect network traffic between the app and the cloud. 

Please let me know, what option do you prefer. If you decide to not to share your password, I'll prepare a guide what exactly you need to do in order to provide me the list of saved requests made to the cloud, so I could start working on it.

Thanks!

**Comment by tomekkleszcz** [comment]
@FrankGeraldLieuwen I've published the `0.0.3-beta.1` version. Could you download and check if every functionality of your purifier works? A lot of things are the same as in my Well A7 air purifier, so I assume it should work with a little bit of code modifications. 

Please also let me know if there are any features that my plugin does not support. I know the Ionizer is not supported by Homekit, but I'll implement it both to Well A7 and Pure A9/AX 9 air conditioners.

Thanks!

**Comment by FrankGeraldLieuwen** [comment]
@tomekkleszcz works like a charm indeed!
![Scherm­afbeelding 2023-07-05 om 15 18 05](https://github.com/tomekkleszcz/homebridge-electrolux-devices/assets/138660099/273001eb-2bb0-44c8-9a12-f4f3c18597ce)

**Comment by FrankGeraldLieuwen** [comment]
One last minor issue with the measurements.

The plugin warns that the COL2 levels are to high while the AX9 doesn't measure carbon dioxide.
On the other hand the Pm1 measurement seems to be missing, maybe there's a mix-up.

Can you add the PM1 levels at the air quality tab and remove the CO2 levels?
![Scherm­afbeelding 2023-07-05 om 20 24 26](https://github.com/tomekkleszcz/homebridge-electrolux-devices/assets/138660099/cf497fe6-d8a7-429b-9d10-6f2d7751478c)

**Comment by tomekkleszcz** [comment]
@FrankGeraldLieuwen I'll check that this afternoon! Thanks!

In terms of PM1 Homekit and Homebridge seems to not support it: https://developers.homebridge.io/#/service/AirQualitySensor I'll try to find another way to implement it.

**Comment by FrankGeraldLieuwen** [comment]
Thank you, just installed the new version and it looks good.
The CO2 measurement is still there as an alarm sensor but please leave it there, if it's in the API I consider it a bonus.
PM1 is not that important if it's not supported, the 2,5 and 10 are after all.

Cheers

Frank

**Comment by tomekkleszcz** [comment]
> Thank you, just installed the new version and it looks good. The CO2 measurement is still there as an alarm sensor but please leave it there, if it's in the API I consider it a bonus. PM1 is not that important if it's not supported, the 2,5 and 10 are after all.
> 
> Cheers
> 
> Frank

I wonder what is the reason they do not show the CO2 readings in the app. For example my Electrolux air purifier has a ECO2 sensor, meaning the CO2 level is estimated. I'll add this reading back again, but I'll mark it as probably being not reliable. We could test it if it works by putting another CO2 sensor next to the air purifier and comparing the results.

Tomorrow, I'll work on the Ionizer feature - it will be present as a switch in the Home app.

**Comment by FrankGeraldLieuwen** [comment]
Well I accidentally have two CO2 meters in one room.
The first is a Netatmo weather station (which should and quite OK) and the other is the AZ which looks te about 10% higher.
![Scherm­afbeelding 2023-07-06 om 19 11 50](https://github.com/tomekkleszcz/homebridge-electrolux-devices/assets/138660099/10551baa-1e54-4e47-85e4-0d31e015b902)
![Scherm­afbeelding 2023-07-06 om 19 11 55](https://github.com/tomekkleszcz/homebridge-electrolux-devices/assets/138660099/d23c0d6c-46c1-4f45-b26d-13afbb9834ff)

**Comment by tomekkleszcz** [comment]
> Well I accidentally have two CO2 meters in one room. The first is a Netatmo weather station (which should and quite OK) and the other is the AZ which looks te about 10% higher. ![Scherm­afbeelding 2023-07-06 om 19 11 50](https://user-images.githubusercontent.com/138660099/251523151-10551baa-1e54-4e47-85e4-0d31e015b902.png) ![Scherm­afbeelding 2023-07-06 om 19 11 55](https://user-images.githubusercontent.com/138660099/251523153-d23c0d6c-46c1-4f45-b26d-13afbb9834ff.png) If you are able to build in an offset, it should be good to go right?

So the offset between these 2 sensors is only 41 ppm? I think it's not a huge difference, both readings could be right because the CO2 level is not the same in every place in the particular room I guess. 

Also, in the previous version the alarm was triggered above 1,000 ppm. I think I could add the configurable value to the config when the alarm is actually triggered. According to the Electrolux app, 1,000 ppm is a potentially hazardous level, however, many sources on the Internet claim that 10,000 ppm is hazardous. I'm not an air quality specialist, so I think I'll add this option to the config with the default value of 1,000 ppm.

**Comment by FrankGeraldLieuwen** [comment]
CO2 measurements are quite a bit off now, did you change a thing on this?
![Scherm­afbeelding 2023-07-07 om 13 56 45](https://github.com/tomekkleszcz/homebridge-electrolux-devices/assets/138660099/28a3342d-704a-4d01-89e4-7233e2517443)
![Scherm­afbeelding 2023-07-07 om 13 57 01](https://github.com/tomekkleszcz/homebridge-electrolux-devices/assets/138660099/84ff5697-824a-4e34-a0eb-83d584270e1e)

**Comment by tomekkleszcz** [comment]
> CO2 measurements are quite a bit off now, did you change a thing on this? ![Scherm­afbeelding 2023-07-07 om 13 56 45](https://user-images.githubusercontent.com/138660099/251733676-28a3342d-704a-4d01-89e4-7233e2517443.png) ![Scherm­afbeelding 2023-07-07 om 13 57 01](https://user-images.githubusercontent.com/138660099/251733684-84ff5697-824a-4e34-a0eb-83d584270e1e.png)

If the readings are off, that means the Electrolux/AEG put the sensor in the device, however later on they've decided it is not reliable enough to expose its readings in the app. I'll create a separate issue for disabling the CO2 sensor in the Homebridge config.
