### ISSUE TITLE
Fan speed for the Well A7 air purifier

### ISSUE THREAD

**Issue by sirzielarz** [tomekkleszcz/homebridge-electrolux-devices#12]
First of all, as usual, thank you so much for the plugin, everything related to Comfort 600 air conditioner works perfectly fine (well at least there's nothing that's not mentioned in current issues :D)

Is there a possibility to turn the Well A7 air purifier to manual mode and control the fan speed?

**Comment by tomekkleszcz** [comment]
@sirzielarz There should be an option in your device to set the mode to "Manual" and change the fan speed to your desired value. Attaching the screenshot so you can take a look how it looks on my iPhone.

![Zrzut ekranu 2024-03-01 o 21 35 21](https://github.com/tomekkleszcz/homebridge-electrolux-devices/assets/4775112/77045ba2-4736-461b-af31-749b915ada95)

Let me know if you're able to do it. Otherwise, I'll reopen the issue, ask for your Electrolux credentials, so I can take a further look. Thanks!
